jobs:
  - job: Lint

    pool:
      vmImage: ubuntu-latest

    steps:
      - template: ../steps/init-node.yml

      - script: npx run-s test:lint-1 test:lint-2
        displayName: Run linter
        timeoutInMinutes: 5

    cancelTimeoutInMinutes: 1
