parameters:
  name: Linux
  vmImage: ubuntu-latest
  nodeVersions:
    - 8.3.0
    - 8.x
    - 9.0.0
    - 9.x
    - 10.0.0
    - 10.x
    - 11.0.0
    - 11.x
    - 12.0.0
    - 12.x
    - 13.0.0
    - 13.x

jobs:
  - job: ${{ format('UnitTest_{0}', parameters.name) }}
    displayName: ${{ format('UnitTest / {0}', parameters.name) }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        ${{ each nodeVersion in parameters.nodeVersions }}:
          ${{ format('Node.js {0}', nodeVersion) }}:
            node_version: ${{ nodeVersion }}

    steps:
      - template: ../steps/init-node.yml
        parameters:
          nodeVersion: $(node_version)

      - script: npm run test:unit-test
        displayName: Run unit test
        timeoutInMinutes: 5

    cancelTimeoutInMinutes: 1
